# Generated by Django 4.2 on 2023-04-15 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderMovie",
        ),
    ]
